build:
  environment:
    php:
      version: 8.2
    variables:
      XDEBUG_MODE: coverage
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests: true
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: clover


filter:
  excluded_paths:
    - bin/*
    - tests/*

checks:
  php:
    code_rating: true
    custom_coding_standard:
      ruleset_path: 'phpcs.xml'

tools:
  php_cs_fixer:
    enabled: true
    extensions:
      - php
    filter:
      excluded_paths:
        - bin/*
        - tests/*

  php_sim:
    enabled: true
    min_mass: 30

  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php

  php_analyzer:
    enabled: true
    extensions:
      - php

  php_hhvm:
    enabled: true
    command: hhvm
    extensions:
      - php

