build:
  nodes:
    my-tests:
      environment:
        php:
          version: 8.2
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: clover


filter:
  excluded_paths:
    - bin/*
    - tests/*

checks:
  php:
    code_rating: true
    custom_coding_standard:
      ruleset_path: 'phpcs.xml'

tools:
  external_code_coverage:
    timeout: 1800
    runs: 2

  php_cs_fixer:
    enabled: true
    extensions:
      - php
    filter:
      excluded_paths:
        - bin/*
        - tests/*

  php_sim:
    enabled: true
    min_mass: 30

  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php

  php_analyzer:
    enabled: true
    extensions:
      - php

  php_hhvm:
    enabled: true
    command: hhvm
    extensions:
      - php

