filter:
  excluded_paths:
    - bin/*
    - tests/*

checks:
  php:
    code_rating: true
    custom_coding_standard:
      ruleset_path: 'phpcs.xml'

tools:
  external_code_coverage: true
    timeout: 600
    runs: 2

  php_cs_fixer:
    enabled: true
    filter:
      excluded_paths:
        - bin/*
        - tests/*
    extensions:
      - php

  php_sim:
    enabled: true
    min_mass: 30

  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php

  php_analyzer:
    enabled: true
    extensions:
      - php

  php_hhvm:
    enabled: true
    command: hhvm
    extensions:
      - php