name: Code style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          verboseMode: true
          testMode: true
          configPath: ./pint.json
